name: gandakimun
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/librsary/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.20+20

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependency_overrides:
  ffi: ^2.0.1
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  responsive_sizer: ^3.0.8
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  http: ^0.13.4
  cached_network_image: ^3.2.0
  photo_view: ^0.14.0
  url_launcher: ^6.1.2
  webview_flutter: ^2.0.4
  file_picker: ^5.2.5
  path_provider:
  path: ^1.8.2
  image_picker: ^0.8.5+3
  get_storage: ^2.0.3
  fluttertoast: ^8.0.9
  table_calendar: ^3.0.6
  introduction_screen: ^3.0.2
  restart_app: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  firebase_messaging: ^14.1.4
  firebase_core: ^2.4.0
  flutter_local_notifications: ^9.7.0
  sqflite: ^2.2.3
  open_file_plus: ^3.4.0
  flutter_facebook_auth: ^5.0.8
  animated_text_kit: ^4.2.2
  dropdown_button2: ^1.7.2
  nepali_utils: ^3.0.3
  ffi: ^2.0.1
  grouped_list: ^5.1.2
  flutter_html: ^3.0.0-alpha.6
  # for pdf view
  flutter_pdfview: ^1.2.5
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  text_scroll: ^0.1.2
  api_cache_manager: ^1.0.2
  shimmer: ^2.0.0
  syncfusion_flutter_pdfviewer: ^20.4.52
  marquee: ^2.2.3
  permission_handler: ^11.3.1
  downloads_path_provider_28:
  flutter_widget_from_html_core: ^0.10.0
  share_plus: ^6.3.1
  qr_code_scanner: ^1.0.1
  in_app_update: ^4.0.1
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
#  firebase_messaging:
#  flutter_local_notifications:
#  firebase_core:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/main_logo.png"
#  adaptive_icon_background: "#ffffff"
#  adaptive_icon_foreground: "assets/main_logo.png"
